import { Medicine } from '../types'

export const medicines: Medicine[] = [
  { id: 1, name: 'Aspirin', price: 10, manufacturer: 'Bayer' },
  { id: 2, name: 'Paracetamol', price: 8, manufacturer: 'Tylenol' },
  { id: 3, name: 'Ibuprofen', price: 15, manufacturer: 'Advil' },
  { id: 4, name: 'Amoxicillin', price: 20, manufacturer: 'GlaxoSmithKline' },
  { id: 5, name: 'Ciprofloxacin', price: 25, manufacturer: 'Bayer' },
  { id: 6, name: 'Metformin', price: 12, manufacturer: 'Sandoz' },
  { id: 7, name: 'Lisinopril', price: 18, manufacturer: 'Zestril' },
  { id: 8, name: 'Amlodipine', price: 22, manufacturer: 'Norvasc' },
  { id: 9, name: 'Simvastatin', price: 14, manufacturer: 'Zocor' },
  { id: 10, name: 'Omeprazole', price: 19, manufacturer: 'Prilosec' },
  { id: 11, name: 'Losartan', price: 16, manufacturer: 'Cozaar' },
  { id: 12, name: 'Gabapentin', price: 13, manufacturer: 'Neurontin' },
  { id: 13, name: 'Hydrochlorothiazide', price: 7, manufacturer: 'Microzide' },
  { id: 14, name: 'Furosemide', price: 11, manufacturer: 'Lasix' },
  { id: 15, name: 'Pantoprazole', price: 9, manufacturer: 'Protonix' },
  { id: 16, name: 'Fluticasone', price: 17, manufacturer: 'Flonase' },
  { id: 17, name: 'Albuterol', price: 21, manufacturer: 'ProAir' },
  { id: 18, name: 'Levothyroxine', price: 23, manufacturer: 'Synthroid' },
  { id: 19, name: 'Cetirizine', price: 5, manufacturer: 'Zyrtec' },
  { id: 20, name: 'Meloxicam', price: 14, manufacturer: 'Mobic' },
  { id: 21, name: 'Tramadol', price: 6, manufacturer: 'Ultram' },
  { id: 22, name: 'Citalopram', price: 10, manufacturer: 'Celexa' },
  { id: 23, name: 'Duloxetine', price: 20, manufacturer: 'Cymbalta' },
  { id: 24, name: 'Trazodone', price: 18, manufacturer: 'Desyrel' },
  { id: 25, name: 'Valsartan', price: 22, manufacturer: 'Diovan' },
  { id: 26, name: 'Rosuvastatin', price: 24, manufacturer: 'Crestor' },
  { id: 27, name: 'Venlafaxine', price: 19, manufacturer: 'Effexor' },
  { id: 28, name: 'Oxycodone', price: 15, manufacturer: 'OxyContin' },
  { id: 29, name: 'Zolpidem', price: 8, manufacturer: 'Ambien' },
  { id: 30, name: 'Metoprolol', price: 12, manufacturer: 'Lopressor' },
  { id: 31, name: 'Fexofenadine', price: 9, manufacturer: 'Allegra' },
  { id: 32, name: 'Ranitidine', price: 11, manufacturer: 'Zantac' },
  { id: 33, name: 'Acyclovir', price: 13, manufacturer: 'Zovirax' },
  { id: 34, name: 'Clopidogrel', price: 17, manufacturer: 'Plavix' },
  { id: 35, name: 'Warfarin', price: 6, manufacturer: 'Coumadin' },
  { id: 36, name: 'Esomeprazole', price: 23, manufacturer: 'Nexium' },
  { id: 37, name: 'Levofloxacin', price: 24, manufacturer: 'Levaquin' },
  { id: 38, name: 'Mupirocin', price: 20, manufacturer: 'Bactroban' },
  { id: 39, name: 'Doxycycline', price: 18, manufacturer: 'Doryx' },
  { id: 40, name: 'Valacyclovir', price: 21, manufacturer: 'Valtrex' },
  
]
